/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Corona;


import java.awt.HeadlessException;
import java.sql.Connection;
import java.sql.SQLException;
import javax.swing.JOptionPane;


/**
 *
 * @author Inzaghi
 */
public class Awal extends javax.swing.JFrame {

    /**
     * Creates new form Awal
     */
    public static String nama;
    
    public Awal() {
        initComponents();
        setLocationRelativeTo(null);
    } 

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        startButton = new javax.swing.JButton();
        infoButton = new javax.swing.JButton();
        tutorialButton = new javax.swing.JButton();
        highscoreButton = new javax.swing.JButton();
        username = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));

        jPanel1.setPreferredSize(new java.awt.Dimension(400, 500));
        jPanel1.setLayout(null);

        startButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/icon Game/play.png"))); // NOI18N
        startButton.setBorder(null);
        startButton.setBorderPainted(false);
        startButton.setContentAreaFilled(false);
        startButton.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        startButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                startButtonActionPerformed(evt);
            }
        });
        jPanel1.add(startButton);
        startButton.setBounds(150, 250, 90, 40);

        infoButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/icon Game/edukasi.png"))); // NOI18N
        infoButton.setBorder(null);
        infoButton.setContentAreaFilled(false);
        infoButton.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        infoButton.setMargin(new java.awt.Insets(2, 2, 2, 2));
        infoButton.setMaximumSize(new java.awt.Dimension(60, 60));
        infoButton.setMinimumSize(new java.awt.Dimension(60, 60));
        infoButton.setPreferredSize(new java.awt.Dimension(60, 60));
        infoButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                infoButtonActionPerformed(evt);
            }
        });
        jPanel1.add(infoButton);
        infoButton.setBounds(280, 430, 60, 60);

        tutorialButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/icon Game/tutorial.png"))); // NOI18N
        tutorialButton.setContentAreaFilled(false);
        tutorialButton.setHideActionText(true);
        tutorialButton.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        tutorialButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tutorialButtonActionPerformed(evt);
            }
        });
        jPanel1.add(tutorialButton);
        tutorialButton.setBounds(170, 430, 60, 60);

        highscoreButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/icon Game/skor.png"))); // NOI18N
        highscoreButton.setBorderPainted(false);
        highscoreButton.setContentAreaFilled(false);
        highscoreButton.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        highscoreButton.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        highscoreButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                highscoreButtonActionPerformed(evt);
            }
        });
        jPanel1.add(highscoreButton);
        highscoreButton.setBounds(50, 430, 60, 60);

        username.setFont(new java.awt.Font("Futura Bk BT", 1, 14)); // NOI18N
        username.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                usernameActionPerformed(evt);
            }
        });
        jPanel1.add(username);
        username.setBounds(120, 200, 160, 30);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/main.gif"))); // NOI18N
        jLabel2.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jPanel1.add(jLabel2);
        jLabel2.setBounds(0, -70, 510, 660);
        jLabel2.getAccessibleContext().setAccessibleParent(this);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 526, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void startButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_startButtonActionPerformed
        // TODO add your handling code here:

        nama =  username.getText();
        Koneksi.buatAkun(nama);
        this.setVisible(false);
        new MainWindow().setVisible(true);
        
    }//GEN-LAST:event_startButtonActionPerformed

    private void infoButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_infoButtonActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        new Info().setVisible(true);
    }//GEN-LAST:event_infoButtonActionPerformed

    private void tutorialButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tutorialButtonActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        new Tutorial().setVisible(true);
    }//GEN-LAST:event_tutorialButtonActionPerformed

    private void highscoreButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_highscoreButtonActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        new High().setVisible(true);
    }//GEN-LAST:event_highscoreButtonActionPerformed

    private void usernameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_usernameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_usernameActionPerformed

    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Awal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Awal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Awal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Awal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Awal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton highscoreButton;
    private javax.swing.JButton infoButton;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton startButton;
    private javax.swing.JButton tutorialButton;
    private javax.swing.JTextField username;
    // End of variables declaration//GEN-END:variables
}
